// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDljZ56hmn106dRcm-nHI3G7S6MzTmcPuI',
    appId: '1:858207127190:web:d3ce6293c3eb8d0ce064b7',
    messagingSenderId: '858207127190',
    projectId: 'data-at-bat',
    authDomain: 'data-at-bat.firebaseapp.com',
    storageBucket: 'data-at-bat.firebasestorage.app',
    measurementId: 'G-95K34F1WYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaZhLujuztwbCzidm8l_g2eoFQZ9IJNk',
    appId: '1:858207127190:android:8d79c25c4d982a07e064b7',
    messagingSenderId: '858207127190',
    projectId: 'data-at-bat',
    storageBucket: 'data-at-bat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa5medzvA_mi5cHQVHxg8yApP_JTRDR6w',
    appId: '1:858207127190:ios:69e246107718ac84e064b7',
    messagingSenderId: '858207127190',
    projectId: 'data-at-bat',
    storageBucket: 'data-at-bat.firebasestorage.app',
    iosClientId: '858207127190-hh385vivrl4ma5t5gfp63nkkbt973ima.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
